# Claude Theme PowerShell Configuration
# Generated by Set-ClaudeTheme.ps1

# Configurar colores de PSReadLine
if (Get-Module -ListAvailable -Name PSReadLine) {
    Set-PSReadLineOption -Colors @{
        Command            = '#CC785C'
        Comment            = '#A0A0A0'
        ContinuationPrompt = '#A0A0A0'
        Default            = '#EFEFEF'
        Emphasis           = '#D4A574'
        Error              = '#E55A5A'
        InlinePrediction   = '#3A3530'
        Keyword            = '#CC785C'
        ListPrediction     = '#D4A574'
        Member             = '#EFEFEF'
        Number             = '#D4A574'
        Operator           = '#A0A0A0'
        Parameter          = '#D4A574'
        Selection          = '#CC785C'
        String             = '#5AE55A'
        Type               = '#CC785C'
        Variable           = '#D4A574'
    }
}

# Prompt personalizado con colores de Claude
function prompt {
    $lastSuccess = $?
    $statusColor = if ($lastSuccess) { '#CC785C' } else { '#E55A5A' }

    Write-Host ""
    Write-Host "$([char]0x250C)" -NoNewline -ForegroundColor DarkGray
    Write-Host " " -NoNewline
    Write-Host $env:USERNAME -NoNewline -ForegroundColor 'CC785C'
    Write-Host "@" -NoNewline -ForegroundColor DarkGray
    Write-Host $env:COMPUTERNAME -NoNewline -ForegroundColor 'D4A574'
    Write-Host " " -NoNewline
    Write-Host $(Get-Location) -ForegroundColor 'A0A0A0'
    Write-Host "$([char]0x2514)$([char]0x2500)" -NoNewline -ForegroundColor DarkGray
    Write-Host " $([char]0x276F)" -NoNewline -ForegroundColor $statusColor
    return " "
}

Write-Host "Claude Theme loaded!" -ForegroundColor '#CC785C'
